# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 501ed1ed001d8d9d778e59f3ff336e18c7df44cbe1ce2e04ad31db16a09bfa71e0d69d15cfeefde346d4f3bd475e8ac459257000b2e1a89b2cbb4632b9c08434

test:
  secret_key_base: 9cf4e880152e90fdae4d0bd37749b42b35b9910c3519e73528c69373860ee5124c4fbe8fda57828c0a038ac46947b981cc581313da1bc74b33b707564d476ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
